library(lubridate)
library(dplyr)
library(magrittr)
library(stringr)
library(rvest)
library(ggplot2)
library(grid)
library(scales)
library(leaflet)
library(shiny)
library(DT)
library(circlize)
library(readr)
library(plyr)
library(lubridate)
library(magrittr)
library(dplyr)
library(tidyr)
library(tibbletime)
library(ggplot2)
library(randomForest)
library(Metrics)
library(zoo)
library(gbm)
library(MASS)
library(TTR)
library(shiny)
library(shinydashboard)

homeC_clean_all_years$dateTime <- as_datetime(homeC_clean_all_years$dateTime)
homeC_clean_all_years<-as_tbl_time(homeC_clean_all_years,index=dateTime)
homeC_clean_all_years_hourly <- homeC_clean_all_years %>% collapse_by(level_of_data) %>% 
  group_by(dateTime) %>% dplyr::summarise(use = sum(use),gen = sum(gen),temp=mean(temp),
                                          hum=mean(hum), vis = mean(vis), press = mean(press), 
                                          windBearing = mean(windBearing),pricipIntensity = mean(pricipIntensity))
homeC_clean_all_years_hourly$dateTime <- as.Date(homeC_clean_all_years_hourly$dateTime)

write.csv(homeC_clean_all_years_hourly,"homeC_clean_predictors_hourly.csv")